// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package billingcyclerepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TenantBillingCycle struct {
	TenantID     string             `json:"tenant_id"`
	PeriodStart  pgtype.Timestamptz `json:"period_start"`
	PeriodEnd    pgtype.Timestamptz `json:"period_end"`
	LastClosedAt pgtype.Timestamptz `json:"last_closed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
