// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package billingcyclerepo

import (
	"database/sql"
	"time"
)

type TenantBillingCycle struct {
	TenantID     string
	PeriodStart  time.Time
	PeriodEnd    time.Time
	LastClosedAt sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
