// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package billingcyclerepo

import (
	"context"
	"time"
)

const getCycleForTenant = `-- name: GetCycleForTenant :one
SELECT tenant_id, period_start, period_end, last_closed_at, created_at, updated_at FROM tenant_billing_cycle WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetCycleForTenant(ctx context.Context, tenantID string) (TenantBillingCycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleForTenant, tenantID)
	var i TenantBillingCycle
	err := row.Scan(
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.LastClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsDueForCycleClose = `-- name: ListTenantsDueForCycleClose :many
SELECT tenant_id FROM tenant_billing_cycle
WHERE period_end <= now()
`

func (q *Queries) ListTenantsDueForCycleClose(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsDueForCycleClose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBillingCycle = `-- name: UpdateBillingCycle :exec
UPDATE tenant_billing_cycle
SET period_start = $2,
    period_end = $3,
    last_closed_at = now(),
    updated_at = now()
WHERE tenant_id = $1
`

type UpdateBillingCycleParams struct {
	TenantID    string
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) UpdateBillingCycle(ctx context.Context, arg UpdateBillingCycleParams) error {
	_, err := q.db.ExecContext(ctx, updateBillingCycle, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	return err
}
