// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsageRecords struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	CustomerID     int64              `json:"customer_id"`
	SubscriptionID int64              `json:"subscription_id"`
	MeterCode      string             `json:"meter_code"`
	Value          float64            `json:"value"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
