// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type UsageRecord struct {
	ID             string
	TenantID       string
	CustomerID     string
	SubscriptionID string
	MeterCode      string
	Value          float64
	RecordedAt     time.Time
	IdempotencyKey sql.NullString
	Metadata       pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
