// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createUsageRecord = `-- name: CreateUsageRecord :exec
INSERT INTO usage_records (
    id, tenant_id, customer_id, subscription_id,
    meter_code, value, recorded_at, idempotency_key,
    metadata, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, now(), now()
)
`

type CreateUsageRecordParams struct {
	ID             string
	TenantID       string
	CustomerID     string
	SubscriptionID string
	MeterCode      string
	Value          float64
	RecordedAt     time.Time
	IdempotencyKey sql.NullString
	Metadata       pqtype.NullRawMessage
}

func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error {
	_, err := q.db.ExecContext(ctx, createUsageRecord,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.MeterCode,
		arg.Value,
		arg.RecordedAt,
		arg.IdempotencyKey,
		arg.Metadata,
	)
	return err
}

const listUsageBySubscription = `-- name: ListUsageBySubscription :many
SELECT
    id, tenant_id, customer_id, subscription_id,
    meter_code, value, recorded_at, idempotency_key,
    metadata, created_at, updated_at
FROM usage_records
WHERE subscription_id = $1
ORDER BY recorded_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageBySubscriptionParams struct {
	SubscriptionID string
	Limit          int32
	Offset         int32
}

func (q *Queries) ListUsageBySubscription(ctx context.Context, arg ListUsageBySubscriptionParams) ([]UsageRecord, error) {
	rows, err := q.db.QueryContext(ctx, listUsageBySubscription, arg.SubscriptionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageRecord
	for rows.Next() {
		var i UsageRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.MeterCode,
			&i.Value,
			&i.RecordedAt,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
