// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageRecord = `-- name: CreateUsageRecord :exec
INSERT INTO usage_records (
    id, tenant_id, customer_id, subscription_id,
    meter_code, value, recorded_at, idempotency_key,
    metadata, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, now(), now()
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
`

type CreateUsageRecordParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	CustomerID     string             `json:"customer_id"`
	SubscriptionID string             `json:"subscription_id"`
	MeterCode      string             `json:"meter_code"`
	Value          float64            `json:"value"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error {
	_, err := q.db.Exec(ctx, createUsageRecord,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.MeterCode,
		arg.Value,
		arg.RecordedAt,
		arg.IdempotencyKey,
		arg.Metadata,
	)
	return err
}

const listUsageBySubscription = `-- name: ListUsageBySubscription :many
SELECT
    id, tenant_id, customer_id, subscription_id,
    meter_code, value, recorded_at, idempotency_key,
    metadata, created_at, updated_at
FROM usage_records
WHERE subscription_id = $1
ORDER BY recorded_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageBySubscriptionParams struct {
	SubscriptionID string `json:"subscription_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListUsageBySubscription(ctx context.Context, arg ListUsageBySubscriptionParams) ([]UsageRecords, error) {
	rows, err := q.db.Query(ctx, listUsageBySubscription, arg.SubscriptionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageRecords
	for rows.Next() {
		var i UsageRecords
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.MeterCode,
			&i.Value,
			&i.RecordedAt,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
