// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Invoice struct {
	ID             string
	TenantID       string
	CustomerID     sql.NullString
	SubscriptionID sql.NullString
	Status         int16
	CurrencyCode   string
	TotalCents     int64
	SubtotalCents  int64
	TaxCents       int64
	InvoiceNumber  sql.NullString
	IssuedAt       sql.NullTime
	DueAt          sql.NullTime
	PaidAt         sql.NullTime
	Metadata       pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
