// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Invoices struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	Status         int16              `json:"status"`
	CurrencyCode   string             `json:"currency_code"`
	TotalCents     int64              `json:"total_cents"`
	SubtotalCents  int64              `json:"subtotal_cents"`
	TaxCents       int64              `json:"tax_cents"`
	InvoiceNumber  pgtype.Text        `json:"invoice_number"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
