// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :exec
INSERT INTO invoices (id, tenant_id, subscription_id, total_cents, status, issued_at, due_at, metadata, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,now(),now())
`

type CreateInvoiceParams struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	TotalCents     int64              `json:"total_cents"`
	Status         int16              `json:"status"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error {
	_, err := q.db.Exec(ctx, createInvoice,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.TotalCents,
		arg.Status,
		arg.IssuedAt,
		arg.DueAt,
		arg.Metadata,
	)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, subscription_id, total_cents, status, issued_at, due_at, metadata, created_at, updated_at FROM invoices WHERE id = $1
`

type GetInvoiceRow struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	TotalCents     int64              `json:"total_cents"`
	Status         int16              `json:"status"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInvoice(ctx context.Context, id int64) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.TotalCents,
		&i.Status,
		&i.IssuedAt,
		&i.DueAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoicesByTenant = `-- name: ListInvoicesByTenant :many
SELECT id, tenant_id, subscription_id, total_cents, status, issued_at, due_at, metadata, created_at, updated_at FROM invoices WHERE tenant_id = $1 ORDER BY issued_at DESC
`

type ListInvoicesByTenantRow struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	TotalCents     int64              `json:"total_cents"`
	Status         int16              `json:"status"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInvoicesByTenant(ctx context.Context, tenantID int64) ([]ListInvoicesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByTenantRow
	for rows.Next() {
		var i ListInvoicesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.TotalCents,
			&i.Status,
			&i.IssuedAt,
			&i.DueAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
