// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type BillingRun struct {
	ID             int64
	TenantID       int64
	SubscriptionID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	Status         int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
