// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingRuns struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SubscriptionID int64              `json:"subscription_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Status         int16              `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
