// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const getBillingRun = `-- name: GetBillingRun :one
SELECT id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at
FROM billing_runs WHERE id = $1
`

func (q *Queries) GetBillingRun(ctx context.Context, id int64) (BillingRun, error) {
	row := q.db.QueryRowContext(ctx, getBillingRun, id)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingRun = `-- name: InsertBillingRun :exec
INSERT INTO billing_runs (id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
`

type InsertBillingRunParams struct {
	ID             int64
	TenantID       int64
	SubscriptionID int64
	PeriodStart    time.Time
	PeriodEnd      time.Time
	Status         int16
}

func (q *Queries) InsertBillingRun(ctx context.Context, arg InsertBillingRunParams) error {
	_, err := q.db.ExecContext(ctx, insertBillingRun,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
	)
	return err
}

const listBillingRunsBySubscription = `-- name: ListBillingRunsBySubscription :many
SELECT id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at
FROM billing_runs WHERE subscription_id = $1 ORDER BY period_start DESC
`

func (q *Queries) ListBillingRunsBySubscription(ctx context.Context, subscriptionID int64) ([]BillingRun, error) {
	rows, err := q.db.QueryContext(ctx, listBillingRunsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRun
	for rows.Next() {
		var i BillingRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
