// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBillingRun = `-- name: GetBillingRun :one
SELECT id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at
FROM billing_runs WHERE id = $1
`

func (q *Queries) GetBillingRun(ctx context.Context, id int64) (BillingRuns, error) {
	row := q.db.QueryRow(ctx, getBillingRun, id)
	var i BillingRuns
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingRun = `-- name: InsertBillingRun :exec
INSERT INTO billing_runs (id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
`

type InsertBillingRunParams struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	SubscriptionID int64              `json:"subscription_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Status         int16              `json:"status"`
}

func (q *Queries) InsertBillingRun(ctx context.Context, arg InsertBillingRunParams) error {
	_, err := q.db.Exec(ctx, insertBillingRun,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
	)
	return err
}

const listBillingRunsBySubscription = `-- name: ListBillingRunsBySubscription :many
SELECT id, tenant_id, subscription_id, period_start, period_end, status, created_at, updated_at
FROM billing_runs WHERE subscription_id = $1 ORDER BY period_start DESC
`

func (q *Queries) ListBillingRunsBySubscription(ctx context.Context, subscriptionID int64) ([]BillingRuns, error) {
	rows, err := q.db.Query(ctx, listBillingRunsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRuns
	for rows.Next() {
		var i BillingRuns
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
