// Code generated by gomock. DO NOT EDIT.
// source: internal/idempotency/cache.go

package mocks

import (
    "context"
    "reflect"
    "time"

    "github.com/golang/mock/gomock"
    idempotency "github.com/smallbiznis/corebilling/internal/idempotency"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
    ctrl     *gomock.Controller
    recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
    mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
    mock := &MockCache{ctrl: ctrl}
    mock.recorder = &MockCacheMockRecorder{mock}
    return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
    return m.recorder
}

// Delete mocks base method.
func (m *MockCache) Delete(ctx context.Context, tenantID, key string) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "Delete", ctx, tenantID, key)
    ret0, _ := ret[0].(error)
    return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder) Delete(ctx, tenantID, key interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache)(nil).Delete), ctx, tenantID, key)
}

// GetHash mocks base method.
func (m *MockCache) GetHash(ctx context.Context, tenantID, key string) (string, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "GetHash", ctx, tenantID, key)
    ret0, _ := ret[0].(string)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// GetHash indicates an expected call of GetHash.
func (mr *MockCacheMockRecorder) GetHash(ctx, tenantID, key interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockCache)(nil).GetHash), ctx, tenantID, key)
}

// SetHash mocks base method.
func (m *MockCache) SetHash(ctx context.Context, tenantID, key, hash string, ttl time.Duration) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "SetHash", ctx, tenantID, key, hash, ttl)
    ret0, _ := ret[0].(error)
    return ret0
}

// SetHash indicates an expected call of SetHash.
func (mr *MockCacheMockRecorder) SetHash(ctx, tenantID, key, hash, ttl interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHash", reflect.TypeOf((*MockCache)(nil).SetHash), ctx, tenantID, key, hash, ttl)
}

var _ idempotency.Cache = (*MockCache)(nil)

