// Code generated by gomock. DO NOT EDIT.
// source: internal/idempotency/repository.go

package mocks

import (
    "context"
    "reflect"

    "github.com/golang/mock/gomock"
    idempotency "github.com/smallbiznis/corebilling/internal/idempotency"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
    ctrl     *gomock.Controller
    recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
    mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
    mock := &MockRepository{ctrl: ctrl}
    mock.recorder = &MockRepositoryMockRecorder{mock}
    return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
    return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, tenantID, key string) (*idempotency.Record, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "Get", ctx, tenantID, key)
    ret0, _ := ret[0].(*idempotency.Record)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, tenantID, key interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, tenantID, key)
}

// InsertProcessing mocks base method.
func (m *MockRepository) InsertProcessing(ctx context.Context, tenantID, key, requestHash string) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "InsertProcessing", ctx, tenantID, key, requestHash)
    ret0, _ := ret[0].(error)
    return ret0
}

// InsertProcessing indicates an expected call of InsertProcessing.
func (mr *MockRepositoryMockRecorder) InsertProcessing(ctx, tenantID, key, requestHash interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProcessing", reflect.TypeOf((*MockRepository)(nil).InsertProcessing), ctx, tenantID, key, requestHash)
}

// MarkCompleted mocks base method.
func (m *MockRepository) MarkCompleted(ctx context.Context, tenantID, key string, response []byte) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "MarkCompleted", ctx, tenantID, key, response)
    ret0, _ := ret[0].(error)
    return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockRepositoryMockRecorder) MarkCompleted(ctx, tenantID, key, response interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockRepository)(nil).MarkCompleted), ctx, tenantID, key, response)
}

var _ idempotency.Repository = (*MockRepository)(nil)

