// Code generated by MockGen. DO NOT EDIT.
// Source: internal/events/outbox/repository.go

// Package outboxmock is a generated GoMock package.
package outboxmock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	outbox "github.com/smallbiznis/corebilling/internal/events/outbox"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// FetchPendingEvents mocks base method.
func (m *MockOutboxRepository) FetchPendingEvents(ctx context.Context, limit int32, now time.Time) ([]outbox.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPendingEvents", ctx, limit, now)
	ret0, _ := ret[0].([]outbox.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPendingEvents indicates an expected call of FetchPendingEvents.
func (mr *MockOutboxRepositoryMockRecorder) FetchPendingEvents(ctx, limit, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPendingEvents", reflect.TypeOf((*MockOutboxRepository)(nil).FetchPendingEvents), ctx, limit, now)
}

// InsertOutboxEvent mocks base method.
func (m *MockOutboxRepository) InsertOutboxEvent(ctx context.Context, evt *outbox.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutboxEvent", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutboxEvent indicates an expected call of InsertOutboxEvent.
func (mr *MockOutboxRepositoryMockRecorder) InsertOutboxEvent(ctx, evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutboxEvent", reflect.TypeOf((*MockOutboxRepository)(nil).InsertOutboxEvent), ctx, evt)
}

// MarkDispatched mocks base method.
func (m *MockOutboxRepository) MarkDispatched(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDispatched", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDispatched indicates an expected call of MarkDispatched.
func (mr *MockOutboxRepositoryMockRecorder) MarkDispatched(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDispatched", reflect.TypeOf((*MockOutboxRepository)(nil).MarkDispatched), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, id string, nextAttemptAt time.Time, lastError string, retryCount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, nextAttemptAt, lastError, retryCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, id, nextAttemptAt, lastError, retryCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, id, nextAttemptAt, lastError, retryCount)
}

// MoveToDeadLetter mocks base method.
func (m *MockOutboxRepository) MoveToDeadLetter(ctx context.Context, id, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDeadLetter", ctx, id, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToDeadLetter indicates an expected call of MoveToDeadLetter.
func (mr *MockOutboxRepositoryMockRecorder) MoveToDeadLetter(ctx, id, lastError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDeadLetter", reflect.TypeOf((*MockOutboxRepository)(nil).MoveToDeadLetter), ctx, id, lastError)
}
