// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customers struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Email             pgtype.Text        `json:"email"`
	Name              pgtype.Text        `json:"name"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          pgtype.Text        `json:"currency"`
	BillingAddress    []byte             `json:"billing_address"`
	ShippingAddress   []byte             `json:"shipping_address"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
