// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO customers (id, tenant_id, external_reference, email, name, phone, currency, billing_address, shipping_address, metadata, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type CreateParams struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Email             pgtype.Text        `json:"email"`
	Name              pgtype.Text        `json:"name"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          pgtype.Text        `json:"currency"`
	BillingAddress    []byte             `json:"billing_address"`
	ShippingAddress   []byte             `json:"shipping_address"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.TenantID,
		arg.ExternalReference,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.Currency,
		arg.BillingAddress,
		arg.ShippingAddress,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, tenant_id, external_reference, email, name, phone, currency, billing_address, shipping_address, metadata, created_at, updated_at FROM customers WHERE id=$1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (Customers, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Customers
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalReference,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Currency,
		&i.BillingAddress,
		&i.ShippingAddress,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByTenant = `-- name: ListByTenant :many
SELECT id, tenant_id, external_reference, email, name, phone, currency, billing_address, shipping_address, metadata, created_at, updated_at FROM customers WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListByTenant(ctx context.Context, arg ListByTenantParams) ([]Customers, error) {
	rows, err := q.db.Query(ctx, listByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customers
	for rows.Next() {
		var i Customers
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalReference,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.Currency,
			&i.BillingAddress,
			&i.ShippingAddress,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE customers SET tenant_id=$2, external_reference=$3, email=$4, name=$5, phone=$6, currency=$7, billing_address=$8, shipping_address=$9, metadata=$10, updated_at=$11 WHERE id=$1
`

type UpdateParams struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Email             pgtype.Text        `json:"email"`
	Name              pgtype.Text        `json:"name"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          pgtype.Text        `json:"currency"`
	BillingAddress    []byte             `json:"billing_address"`
	ShippingAddress   []byte             `json:"shipping_address"`
	Metadata          []byte             `json:"metadata"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.ID,
		arg.TenantID,
		arg.ExternalReference,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.Currency,
		arg.BillingAddress,
		arg.ShippingAddress,
		arg.Metadata,
		arg.UpdatedAt,
	)
	return err
}
