// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RatingResults struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	UsageID     int64              `json:"usage_id"`
	PriceID     int64              `json:"price_id"`
	AmountCents int64              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
