// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type RatingResult struct {
	ID          int64
	TenantID    int64
	UsageID     int64
	PriceID     int64
	AmountCents int64
	Currency    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
