// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createRatingResult = `-- name: CreateRatingResult :exec
INSERT INTO rating_results (id, tenant_id, usage_id, price_id, amount_cents, currency, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,now(),now())
`

type CreateRatingResultParams struct {
	ID          int64
	TenantID    int64
	UsageID     int64
	PriceID     int64
	AmountCents int64
	Currency    string
}

func (q *Queries) CreateRatingResult(ctx context.Context, arg CreateRatingResultParams) error {
	_, err := q.db.ExecContext(ctx, createRatingResult,
		arg.ID,
		arg.TenantID,
		arg.UsageID,
		arg.PriceID,
		arg.AmountCents,
		arg.Currency,
	)
	return err
}

const getRatingResult = `-- name: GetRatingResult :one
SELECT id, tenant_id, usage_id, price_id, amount_cents, currency, created_at, updated_at FROM rating_results WHERE id = $1
`

func (q *Queries) GetRatingResult(ctx context.Context, id int64) (RatingResult, error) {
	row := q.db.QueryRowContext(ctx, getRatingResult, id)
	var i RatingResult
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UsageID,
		&i.PriceID,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
