// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package idempotencysqlc

import "time"

type IdempotencyRecord struct {
	TenantID    string
	Key         string
	RequestHash string
	Response    []byte
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Query parameter structs.
type GetRecordParams struct {
	TenantID string
	Key      string
}

type InsertProcessingParams struct {
	TenantID    string
	Key         string
	RequestHash string
}

type MarkCompletedParams struct {
	TenantID string
	Key      string
	Response []byte
}
