// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecords struct {
	TenantID    int64              `json:"tenant_id"`
	Key         string             `json:"key"`
	RequestHash string             `json:"request_hash"`
	Response    []byte             `json:"response"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
