// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package idempotencysqlc

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type IdempotencyRecord struct {
	TenantID    string
	Key         string
	RequestHash string
	Response    pqtype.NullRawMessage
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
