// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingEvents struct {
	ID            int64              `json:"id"`
	Subject       string             `json:"subject"`
	TenantID      int64              `json:"tenant_id"`
	ResourceID    pgtype.Int8        `json:"resource_id"`
	EventType     pgtype.Text        `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
