// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package quotarepo

import (
	"database/sql"
	"time"
)

type TenantQuotaLimit struct {
	TenantID             string
	MaxEventsPerDay      int64
	MaxUsageUnits        int64
	SoftWarningThreshold sql.NullFloat64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type TenantQuotaUsage struct {
	TenantID    string
	EventsToday int64
	UsageUnits  int64
	ResetAt     sql.NullTime
	UpdatedAt   time.Time
}
