// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package quotarepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TenantQuotaLimits struct {
	TenantID             string             `json:"tenant_id"`
	MaxEventsPerDay      int64              `json:"max_events_per_day"`
	MaxUsageUnits        int64              `json:"max_usage_units"`
	SoftWarningThreshold pgtype.Float8      `json:"soft_warning_threshold"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TenantQuotaUsage struct {
	TenantID    string             `json:"tenant_id"`
	EventsToday int64              `json:"events_today"`
	UsageUnits  int64              `json:"usage_units"`
	ResetAt     pgtype.Timestamptz `json:"reset_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
