// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package quotarepo

import (
	"context"
)

const getQuotaLimit = `-- name: GetQuotaLimit :one
SELECT tenant_id, max_events_per_day, max_usage_units, soft_warning_threshold, created_at, updated_at FROM tenant_quota_limits WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetQuotaLimit(ctx context.Context, tenantID string) (TenantQuotaLimit, error) {
	row := q.db.QueryRowContext(ctx, getQuotaLimit, tenantID)
	var i TenantQuotaLimit
	err := row.Scan(
		&i.TenantID,
		&i.MaxEventsPerDay,
		&i.MaxUsageUnits,
		&i.SoftWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotaUsage = `-- name: GetQuotaUsage :one
SELECT tenant_id, events_today, usage_units, reset_at, updated_at FROM tenant_quota_usage WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetQuotaUsage(ctx context.Context, tenantID string) (TenantQuotaUsage, error) {
	row := q.db.QueryRowContext(ctx, getQuotaUsage, tenantID)
	var i TenantQuotaUsage
	err := row.Scan(
		&i.TenantID,
		&i.EventsToday,
		&i.UsageUnits,
		&i.ResetAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsOverLimit = `-- name: ListTenantsOverLimit :many
SELECT tenant_quota_usage.tenant_id
FROM tenant_quota_usage
JOIN tenant_quota_limits
  ON tenant_quota_limits.tenant_id = tenant_quota_usage.tenant_id
WHERE events_today > max_events_per_day
   OR usage_units > max_usage_units
`

func (q *Queries) ListTenantsOverLimit(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsOverLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuotaUsage = `-- name: UpsertQuotaUsage :exec
INSERT INTO tenant_quota_usage (tenant_id, events_today, usage_units, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (tenant_id)
DO UPDATE SET events_today = $2, usage_units = $3, updated_at = now()
`

type UpsertQuotaUsageParams struct {
	TenantID    string
	EventsToday int64
	UsageUnits  int64
}

func (q *Queries) UpsertQuotaUsage(ctx context.Context, arg UpsertQuotaUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertQuotaUsage, arg.TenantID, arg.EventsToday, arg.UsageUnits)
	return err
}
