// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meters struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	Code        string             `json:"code"`
	Aggregation int16              `json:"aggregation"`
	Transform   int16              `json:"transform"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
