// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO meters (id, tenant_id, code, aggregation, transform, metadata, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateParams struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	Code        string             `json:"code"`
	Aggregation int16              `json:"aggregation"`
	Transform   int16              `json:"transform"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Aggregation,
		arg.Transform,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, tenant_id, code, aggregation, transform, metadata, created_at, updated_at FROM meters WHERE id=$1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (Meters, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Meters
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Aggregation,
		&i.Transform,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByTenant = `-- name: ListByTenant :many
SELECT id, tenant_id, code, aggregation, transform, metadata, created_at, updated_at FROM meters WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListByTenant(ctx context.Context, arg ListByTenantParams) ([]Meters, error) {
	rows, err := q.db.Query(ctx, listByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meters
	for rows.Next() {
		var i Meters
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Aggregation,
			&i.Transform,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE meters SET tenant_id=$2, code=$3, aggregation=$4, transform=$5, metadata=$6, updated_at=$7 WHERE id=$1
`

type UpdateParams struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	Code        string             `json:"code"`
	Aggregation int16              `json:"aggregation"`
	Transform   int16              `json:"transform"`
	Metadata    []byte             `json:"metadata"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Aggregation,
		arg.Transform,
		arg.Metadata,
		arg.UpdatedAt,
	)
	return err
}
