// Code generated by MockGen. DO NOT EDIT.
// Source: internal/webhook/domain/repository.go

// Package webhookmock is a generated GoMock package.
package webhookmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/smallbiznis/corebilling/internal/webhook/domain"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateDelivery mocks base method.
func (m *MockRepository) CreateDelivery(ctx context.Context, delivery domain.WebhookDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockRepositoryMockRecorder) CreateDelivery(ctx, delivery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockRepository)(nil).CreateDelivery), ctx, delivery)
}

// CreateSubscription mocks base method.
func (m *MockRepository) CreateSubscription(ctx context.Context, subscription domain.WebhookSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockRepositoryMockRecorder) CreateSubscription(ctx, subscription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockRepository)(nil).CreateSubscription), ctx, subscription)
}

// DeleteSubscription mocks base method.
func (m *MockRepository) DeleteSubscription(ctx context.Context, tenantID, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, tenantID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockRepositoryMockRecorder) DeleteSubscription(ctx, tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockRepository)(nil).DeleteSubscription), ctx, tenantID, id)
}

// ListDeliveries mocks base method.
func (m *MockRepository) ListDeliveries(ctx context.Context, subscriptionID string) ([]domain.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeliveries", ctx, subscriptionID)
	ret0, _ := ret[0].([]domain.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeliveries indicates an expected call of ListDeliveries.
func (mr *MockRepositoryMockRecorder) ListDeliveries(ctx, subscriptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeliveries", reflect.TypeOf((*MockRepository)(nil).ListDeliveries), ctx, subscriptionID)
}

// ListSubscriptions mocks base method.
func (m *MockRepository) ListSubscriptions(ctx context.Context, tenantID string) ([]domain.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", ctx, tenantID)
	ret0, _ := ret[0].([]domain.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockRepositoryMockRecorder) ListSubscriptions(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockRepository)(nil).ListSubscriptions), ctx, tenantID)
}
