// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type WebhookDeliveries struct {
	ID             int64              `json:"id"`
	SubscriptionID int64              `json:"subscription_id"`
	EventID        int64              `json:"event_id"`
	Status         int16              `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WebhookDeliveryAttempts struct {
	ID        int64              `json:"id"`
	WebhookID int64              `json:"webhook_id"`
	EventID   int64              `json:"event_id"`
	TenantID  int64              `json:"tenant_id"`
	Payload   json.RawMessage    `json:"payload"`
	Status    string             `json:"status"`
	AttemptNo int32              `json:"attempt_no"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	LastError pgtype.Text        `json:"last_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDlq struct {
	ID        int64              `json:"id"`
	WebhookID int64              `json:"webhook_id"`
	EventID   int64              `json:"event_id"`
	TenantID  string             `json:"tenant_id"`
	Payload   json.RawMessage    `json:"payload"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookSubscriptions struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	Url        string             `json:"url"`
	Status     int16              `json:"status"`
	Secret     pgtype.Text        `json:"secret"`
	EventTypes []string           `json:"event_types"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Webhooks struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	TargetUrl  string             `json:"target_url"`
	Secret     string             `json:"secret"`
	EventTypes []string           `json:"event_types"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
