// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Webhook struct {
	ID         string
	TenantID   string
	TargetUrl  string
	Secret     string
	EventTypes []string
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type WebhookDelivery struct {
	ID             string
	SubscriptionID string
	EventID        string
	Status         int16
	ResponseStatus sql.NullInt32
	ResponseBody   sql.NullString
	DeliveredAt    sql.NullTime
	CreatedAt      time.Time
}

type WebhookDeliveryAttempt struct {
	ID        int64
	WebhookID string
	EventID   string
	TenantID  string
	Payload   json.RawMessage
	Status    string
	AttemptNo int32
	NextRunAt time.Time
	LastError sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WebhookDlq struct {
	ID        int64
	WebhookID string
	EventID   string
	TenantID  string
	Payload   json.RawMessage
	Reason    sql.NullString
	CreatedAt time.Time
}

type WebhookSubscription struct {
	ID         string
	TenantID   string
	Url        string
	Status     int16
	Secret     sql.NullString
	EventTypes []string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
