// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
FROM webhooks
WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TargetUrl,
		&i.Secret,
		pq.Array(&i.EventTypes),
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :one
INSERT INTO webhook_delivery_attempts (
    webhook_id, event_id, tenant_id, payload,
    status, attempt_no, next_run_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
) RETURNING id, webhook_id, event_id, tenant_id, payload, status, attempt_no, next_run_at, last_error, created_at, updated_at
`

type InsertDeliveryAttemptParams struct {
	WebhookID string
	EventID   string
	TenantID  string
	Payload   json.RawMessage
	Status    string
	AttemptNo int32
	NextRunAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) (WebhookDeliveryAttempt, error) {
	row := q.db.QueryRowContext(ctx, insertDeliveryAttempt,
		arg.WebhookID,
		arg.EventID,
		arg.TenantID,
		arg.Payload,
		arg.Status,
		arg.AttemptNo,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebhookDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.TenantID,
		&i.Payload,
		&i.Status,
		&i.AttemptNo,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhook = `-- name: InsertWebhook :one
INSERT INTO webhooks (
    id, tenant_id, target_url, secret,
    event_types, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
) RETURNING id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
`

type InsertWebhookParams struct {
	ID         string
	TenantID   string
	TargetUrl  string
	Secret     string
	EventTypes []string
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) InsertWebhook(ctx context.Context, arg InsertWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, insertWebhook,
		arg.ID,
		arg.TenantID,
		arg.TargetUrl,
		arg.Secret,
		pq.Array(arg.EventTypes),
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TargetUrl,
		&i.Secret,
		pq.Array(&i.EventTypes),
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueDeliveryAttempts = `-- name: ListDueDeliveryAttempts :many
SELECT id, webhook_id, event_id, tenant_id, payload, status, attempt_no, next_run_at, last_error, created_at, updated_at
FROM webhook_delivery_attempts
WHERE status = 'PENDING'
  AND next_run_at <= $1
ORDER BY next_run_at
LIMIT $2
`

type ListDueDeliveryAttemptsParams struct {
	NextRunAt time.Time
	Limit     int32
}

func (q *Queries) ListDueDeliveryAttempts(ctx context.Context, arg ListDueDeliveryAttemptsParams) ([]WebhookDeliveryAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listDueDeliveryAttempts, arg.NextRunAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDeliveryAttempt
	for rows.Next() {
		var i WebhookDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.TenantID,
			&i.Payload,
			&i.Status,
			&i.AttemptNo,
			&i.NextRunAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByTenant = `-- name: ListWebhooksByTenant :many
SELECT id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
FROM webhooks
WHERE tenant_id = $1
  AND enabled
  AND ($2::TEXT IS NULL OR $2 = ANY(event_types))
ORDER BY created_at DESC
`

type ListWebhooksByTenantParams struct {
	TenantID string
	Column2  string
}

func (q *Queries) ListWebhooksByTenant(ctx context.Context, arg ListWebhooksByTenantParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByTenant, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TargetUrl,
			&i.Secret,
			pq.Array(&i.EventTypes),
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveToDLQ = `-- name: MoveToDLQ :exec
WITH inserted AS (
    INSERT INTO webhook_dlq (webhook_id, event_id, tenant_id, payload, reason, created_at)
    VALUES ($1, $2, $3, $4, $5, NOW())
)
UPDATE webhook_delivery_attempts
SET status = 'DLQ',
    updated_at = NOW()
WHERE webhook_delivery_attempts.id = $6
`

type MoveToDLQParams struct {
	WebhookID string
	EventID   string
	TenantID  string
	Payload   json.RawMessage
	Reason    sql.NullString
	ID        int64
}

func (q *Queries) MoveToDLQ(ctx context.Context, arg MoveToDLQParams) error {
	_, err := q.db.ExecContext(ctx, moveToDLQ,
		arg.WebhookID,
		arg.EventID,
		arg.TenantID,
		arg.Payload,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateDeliveryAttemptStatus = `-- name: UpdateDeliveryAttemptStatus :exec
UPDATE webhook_delivery_attempts
SET status = $2,
    attempt_no = $3,
    next_run_at = $4,
    last_error = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeliveryAttemptStatusParams struct {
	ID        int64
	Status    string
	AttemptNo int32
	NextRunAt time.Time
	LastError sql.NullString
}

func (q *Queries) UpdateDeliveryAttemptStatus(ctx context.Context, arg UpdateDeliveryAttemptStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryAttemptStatus,
		arg.ID,
		arg.Status,
		arg.AttemptNo,
		arg.NextRunAt,
		arg.LastError,
	)
	return err
}
