// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
FROM webhooks
WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhooks, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhooks
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :one
INSERT INTO webhook_delivery_attempts (
    webhook_id, event_id, tenant_id, payload,
    status, attempt_no, next_run_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
) RETURNING id, webhook_id, event_id, tenant_id, payload, status, attempt_no, next_run_at, last_error, created_at, updated_at
`

type InsertDeliveryAttemptParams struct {
	WebhookID string             `json:"webhook_id"`
	EventID   string             `json:"event_id"`
	TenantID  string             `json:"tenant_id"`
	Payload   json.RawMessage    `json:"payload"`
	Status    string             `json:"status"`
	AttemptNo int32              `json:"attempt_no"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) (WebhookDeliveryAttempts, error) {
	row := q.db.QueryRow(ctx, insertDeliveryAttempt,
		arg.WebhookID,
		arg.EventID,
		arg.TenantID,
		arg.Payload,
		arg.Status,
		arg.AttemptNo,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebhookDeliveryAttempts
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.TenantID,
		&i.Payload,
		&i.Status,
		&i.AttemptNo,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhook = `-- name: InsertWebhook :one
INSERT INTO webhooks (
    id, tenant_id, target_url, secret,
    event_types, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
) RETURNING id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
`

type InsertWebhookParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	TargetUrl  string             `json:"target_url"`
	Secret     string             `json:"secret"`
	EventTypes []string           `json:"event_types"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertWebhook(ctx context.Context, arg InsertWebhookParams) (Webhooks, error) {
	row := q.db.QueryRow(ctx, insertWebhook,
		arg.ID,
		arg.TenantID,
		arg.TargetUrl,
		arg.Secret,
		arg.EventTypes,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhooks
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueDeliveryAttempts = `-- name: ListDueDeliveryAttempts :many
SELECT id, webhook_id, event_id, tenant_id, payload, status, attempt_no, next_run_at, last_error, created_at, updated_at
FROM webhook_delivery_attempts
WHERE status = 'PENDING'
  AND next_run_at <= $1
ORDER BY next_run_at
LIMIT $2
`

type ListDueDeliveryAttemptsParams struct {
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListDueDeliveryAttempts(ctx context.Context, arg ListDueDeliveryAttemptsParams) ([]WebhookDeliveryAttempts, error) {
	rows, err := q.db.Query(ctx, listDueDeliveryAttempts, arg.NextRunAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDeliveryAttempts
	for rows.Next() {
		var i WebhookDeliveryAttempts
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.TenantID,
			&i.Payload,
			&i.Status,
			&i.AttemptNo,
			&i.NextRunAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByTenant = `-- name: ListWebhooksByTenant :many
SELECT id, tenant_id, target_url, secret, event_types, enabled, created_at, updated_at
FROM webhooks
WHERE tenant_id = $1
  AND enabled
  AND ($2::TEXT IS NULL OR $2 = ANY(event_types))
ORDER BY created_at DESC
`

type ListWebhooksByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Column2  string `json:"column_2"`
}

func (q *Queries) ListWebhooksByTenant(ctx context.Context, arg ListWebhooksByTenantParams) ([]Webhooks, error) {
	rows, err := q.db.Query(ctx, listWebhooksByTenant, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhooks
	for rows.Next() {
		var i Webhooks
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TargetUrl,
			&i.Secret,
			&i.EventTypes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveToDLQ = `-- name: MoveToDLQ :exec
WITH inserted AS (
    INSERT INTO webhook_dlq (webhook_id, event_id, tenant_id, payload, reason, created_at)
    VALUES ($1, $2, $3, $4, $5, NOW())
)
UPDATE webhook_delivery_attempts
SET status = 'DLQ',
    updated_at = NOW()
WHERE webhook_delivery_attempts.id = $6
`

type MoveToDLQParams struct {
	WebhookID string          `json:"webhook_id"`
	EventID   string          `json:"event_id"`
	TenantID  string          `json:"tenant_id"`
	Payload   json.RawMessage `json:"payload"`
	Reason    pgtype.Text     `json:"reason"`
	ID        int64           `json:"id"`
}

func (q *Queries) MoveToDLQ(ctx context.Context, arg MoveToDLQParams) error {
	_, err := q.db.Exec(ctx, moveToDLQ,
		arg.WebhookID,
		arg.EventID,
		arg.TenantID,
		arg.Payload,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateDeliveryAttemptStatus = `-- name: UpdateDeliveryAttemptStatus :exec
UPDATE webhook_delivery_attempts
SET status = $2,
    attempt_no = $3,
    next_run_at = $4,
    last_error = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeliveryAttemptStatusParams struct {
	ID        int64              `json:"id"`
	Status    string             `json:"status"`
	AttemptNo int32              `json:"attempt_no"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	LastError pgtype.Text        `json:"last_error"`
}

func (q *Queries) UpdateDeliveryAttemptStatus(ctx context.Context, arg UpdateDeliveryAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryAttemptStatus,
		arg.ID,
		arg.Status,
		arg.AttemptNo,
		arg.NextRunAt,
		arg.LastError,
	)
	return err
}
