// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Subscription struct {
	ID                 string
	TenantID           string
	CustomerID         string
	PriceID            string
	Status             int16
	AutoRenew          bool
	StartAt            time.Time
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	TrialStartAt       sql.NullTime
	TrialEndAt         sql.NullTime
	CancelAt           sql.NullTime
	CanceledAt         sql.NullTime
	Metadata           pqtype.NullRawMessage
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
