// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenants struct {
	ID              int64              `json:"id"`
	ParentID        pgtype.Int8        `json:"parent_id"`
	Type            int16              `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Status          int16              `json:"status"`
	DefaultCurrency pgtype.Text        `json:"default_currency"`
	CountryCode     pgtype.Text        `json:"country_code"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
