// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO tenants (
			id, parent_id, type, name, slug, status, default_currency, country_code, metadata, created_at, updated_at
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type CreateParams struct {
	ID              int64              `json:"id"`
	ParentID        pgtype.Int8        `json:"parent_id"`
	Type            int16              `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Status          int16              `json:"status"`
	DefaultCurrency pgtype.Text        `json:"default_currency"`
	CountryCode     pgtype.Text        `json:"country_code"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.ParentID,
		arg.Type,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.DefaultCurrency,
		arg.CountryCode,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, parent_id, type, name, slug, status, default_currency, country_code, metadata, created_at, updated_at
		FROM tenants WHERE id=$1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (Tenants, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DefaultCurrency,
		&i.CountryCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, parent_id, type, name, slug, status, default_currency, country_code, metadata, created_at, updated_at
		FROM tenants WHERE $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]Tenants, error) {
	rows, err := q.db.Query(ctx, list, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenants
	for rows.Next() {
		var i Tenants
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.DefaultCurrency,
			&i.CountryCode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
