// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Price struct {
	ID                   int64
	TenantID             int64
	ProductID            int64
	Code                 string
	LookupKey            sql.NullString
	PricingModel         int16
	Currency             string
	UnitAmountCents      int64
	BillingInterval      int16
	BillingIntervalCount int32
	Active               bool
	Metadata             pqtype.NullRawMessage
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type PriceTier struct {
	ID              int64
	PriceID         int64
	StartQuantity   float64
	EndQuantity     float64
	UnitAmountCents int64
	Unit            string
	Metadata        pqtype.NullRawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Product struct {
	ID          int64
	TenantID    int64
	Name        string
	Code        string
	Description sql.NullString
	Active      bool
	Metadata    pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
