// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PriceTiers struct {
	ID              int64              `json:"id"`
	PriceID         int64              `json:"price_id"`
	StartQuantity   float64            `json:"start_quantity"`
	EndQuantity     float64            `json:"end_quantity"`
	UnitAmountCents int64              `json:"unit_amount_cents"`
	Unit            string             `json:"unit"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Prices struct {
	ID                   int64              `json:"id"`
	TenantID             int64              `json:"tenant_id"`
	ProductID            int64              `json:"product_id"`
	Code                 string             `json:"code"`
	LookupKey            pgtype.Text        `json:"lookup_key"`
	PricingModel         int16              `json:"pricing_model"`
	Currency             string             `json:"currency"`
	UnitAmountCents      int64              `json:"unit_amount_cents"`
	BillingInterval      int16              `json:"billing_interval"`
	BillingIntervalCount int32              `json:"billing_interval_count"`
	Active               bool               `json:"active"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Products struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
