// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getPriceByID = `-- name: GetPriceByID :one
SELECT id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
FROM prices
WHERE tenant_id = $1 AND id = $2
`

type GetPriceByIDParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) GetPriceByID(ctx context.Context, arg GetPriceByIDParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, getPriceByID, arg.TenantID, arg.ID)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.LookupKey,
		&i.PricingModel,
		&i.Currency,
		&i.UnitAmountCents,
		&i.BillingInterval,
		&i.BillingIntervalCount,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, name, code, description, active, metadata, created_at, updated_at
FROM products
WHERE tenant_id = $1 AND id = $2
`

type GetProductByIDParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, arg.TenantID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrice = `-- name: InsertPrice :one
INSERT INTO prices (
    id, tenant_id, product_id, code,
    lookup_key, pricing_model, currency,
    unit_amount_cents, billing_interval,
    billing_interval_count, active, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11, $12
) RETURNING id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
`

type InsertPriceParams struct {
	ID                   int64
	TenantID             int64
	ProductID            int64
	Code                 string
	LookupKey            sql.NullString
	PricingModel         int16
	Currency             string
	UnitAmountCents      int64
	BillingInterval      int16
	BillingIntervalCount int32
	Active               bool
	Metadata             pqtype.NullRawMessage
}

func (q *Queries) InsertPrice(ctx context.Context, arg InsertPriceParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, insertPrice,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.Code,
		arg.LookupKey,
		arg.PricingModel,
		arg.Currency,
		arg.UnitAmountCents,
		arg.BillingInterval,
		arg.BillingIntervalCount,
		arg.Active,
		arg.Metadata,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.LookupKey,
		&i.PricingModel,
		&i.Currency,
		&i.UnitAmountCents,
		&i.BillingInterval,
		&i.BillingIntervalCount,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
    id, tenant_id, name, code, description, active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, name, code, description, active, metadata, created_at, updated_at
`

type InsertProductParams struct {
	ID          int64
	TenantID    int64
	Name        string
	Code        string
	Description sql.NullString
	Active      bool
	Metadata    pqtype.NullRawMessage
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Active,
		arg.Metadata,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPricesWithFilter = `-- name: ListPricesWithFilter :many
SELECT id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
FROM prices
WHERE tenant_id = $1
  AND ($2::BIGINT IS NULL OR product_id = $2)
  AND ($3::TEXT IS NULL OR code = $3)
ORDER BY id
LIMIT $4 OFFSET $5
`

type ListPricesWithFilterParams struct {
	TenantID int64
	Column2  int64
	Column3  string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPricesWithFilter(ctx context.Context, arg ListPricesWithFilterParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPricesWithFilter,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Code,
			&i.LookupKey,
			&i.PricingModel,
			&i.Currency,
			&i.UnitAmountCents,
			&i.BillingInterval,
			&i.BillingIntervalCount,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByTenant = `-- name: ListProductsByTenant :many
SELECT id, tenant_id, name, code, description, active, metadata, created_at, updated_at
FROM products
WHERE tenant_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListProductsByTenantParams struct {
	TenantID int64
	Limit    int32
	Offset   int32
}

func (q *Queries) ListProductsByTenant(ctx context.Context, arg ListProductsByTenantParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
