// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPriceByID = `-- name: GetPriceByID :one
SELECT id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
FROM prices
WHERE tenant_id = $1 AND id = $2
`

type GetPriceByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetPriceByID(ctx context.Context, arg GetPriceByIDParams) (Prices, error) {
	row := q.db.QueryRow(ctx, getPriceByID, arg.TenantID, arg.ID)
	var i Prices
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.LookupKey,
		&i.PricingModel,
		&i.Currency,
		&i.UnitAmountCents,
		&i.BillingInterval,
		&i.BillingIntervalCount,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, tenant_id, name, code, description, active, metadata, created_at, updated_at
FROM products
WHERE tenant_id = $1 AND id = $2
`

type GetProductByIDParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Products, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.TenantID, arg.ID)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrice = `-- name: InsertPrice :one
INSERT INTO prices (
    id, tenant_id, product_id, code,
    lookup_key, pricing_model, currency,
    unit_amount_cents, billing_interval,
    billing_interval_count, active, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11, $12
) RETURNING id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
`

type InsertPriceParams struct {
	ID                   int64       `json:"id"`
	TenantID             int64       `json:"tenant_id"`
	ProductID            int64       `json:"product_id"`
	Code                 string      `json:"code"`
	LookupKey            pgtype.Text `json:"lookup_key"`
	PricingModel         int16       `json:"pricing_model"`
	Currency             string      `json:"currency"`
	UnitAmountCents      int64       `json:"unit_amount_cents"`
	BillingInterval      int16       `json:"billing_interval"`
	BillingIntervalCount int32       `json:"billing_interval_count"`
	Active               bool        `json:"active"`
	Metadata             []byte      `json:"metadata"`
}

func (q *Queries) InsertPrice(ctx context.Context, arg InsertPriceParams) (Prices, error) {
	row := q.db.QueryRow(ctx, insertPrice,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.Code,
		arg.LookupKey,
		arg.PricingModel,
		arg.Currency,
		arg.UnitAmountCents,
		arg.BillingInterval,
		arg.BillingIntervalCount,
		arg.Active,
		arg.Metadata,
	)
	var i Prices
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.LookupKey,
		&i.PricingModel,
		&i.Currency,
		&i.UnitAmountCents,
		&i.BillingInterval,
		&i.BillingIntervalCount,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
    id, tenant_id, name, code, description, active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, name, code, description, active, metadata, created_at, updated_at
`

type InsertProductParams struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Active,
		arg.Metadata,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPricesWithFilter = `-- name: ListPricesWithFilter :many
SELECT id, tenant_id, product_id, code, lookup_key, pricing_model, currency, unit_amount_cents, billing_interval, billing_interval_count, active, metadata, created_at, updated_at
FROM prices
WHERE tenant_id = $1
  AND ($2::BIGINT IS NULL OR product_id = $2)
  AND ($3::TEXT IS NULL OR code = $3)
ORDER BY id
LIMIT $4 OFFSET $5
`

type ListPricesWithFilterParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  int64  `json:"column_2"`
	Column3  string `json:"column_3"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListPricesWithFilter(ctx context.Context, arg ListPricesWithFilterParams) ([]Prices, error) {
	rows, err := q.db.Query(ctx, listPricesWithFilter,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prices
	for rows.Next() {
		var i Prices
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Code,
			&i.LookupKey,
			&i.PricingModel,
			&i.Currency,
			&i.UnitAmountCents,
			&i.BillingInterval,
			&i.BillingIntervalCount,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByTenant = `-- name: ListProductsByTenant :many
SELECT id, tenant_id, name, code, description, active, metadata, created_at, updated_at
FROM products
WHERE tenant_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListProductsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListProductsByTenant(ctx context.Context, arg ListProductsByTenantParams) ([]Products, error) {
	rows, err := q.db.Query(ctx, listProductsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
